name: Ensure PR is labeled

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}


jobs:
  check-type-label:
    name: Check [Type] Label
    runs-on: ubuntu-latest
    steps:
      - if: contains( env.LABELS, '[Type]' ) == false
        run: exit 1
